# Generated by Django 3.2.23 on 2024-06-29 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_driver_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ower',
            name='city',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
