# Generated by Django 3.2.23 on 2024-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_ower_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='ower',
            name='status',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
