# Generated by Django 3.2.23 on 2024-06-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_ower_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='OWER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ower'),
            preserve_default=False,
        ),
    ]
