# Generated by Django 3.2.23 on 2024-07-01 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bus_ower'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ower',
            new_name='Owner',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='Passenger',
        ),
        migrations.RemoveField(
            model_name='allocation',
            name='ROUTE',
        ),
        migrations.AddField(
            model_name='allocation',
            name='DRIVER',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
        ),
        migrations.AddField(
            model_name='bus',
            name='BUSROUTE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.route'),
        ),
        migrations.AddField(
            model_name='complaints',
            name='BUS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bus'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='stops',
            name='charge',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Checkin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
                ('Checkin_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromstop', to='app.stops')),
                ('Checkout_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tostop', to='app.stops')),
                ('PASSENGER', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.passenger')),
            ],
        ),
    ]
