# Generated by Django 3.2.23 on 2024-07-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20240701_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='BUSROUTE',
            new_name='ROUTE',
        ),
    ]
