# Generated by Django 3.2.23 on 2024-07-01 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_busroute_bus_route'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
