# Generated by Django 3.2.23 on 2024-07-02 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_bus_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ROUTE',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
