# Generated by Django 3.2.23 on 2024-07-02 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20240702_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='allocation',
            name='OWER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='allocation',
            name='ROUTE',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.route'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stops',
            name='lattitude',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='stops',
            name='longitude',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=200)),
                ('End_time', models.CharField(max_length=200)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bus')),
                ('ROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.route')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('PASSENGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.passenger')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=200)),
                ('reply', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('PASSENGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.passenger')),
            ],
        ),
    ]
