# Generated by Django 3.2.23 on 2024-07-03 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20240702_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='BUS',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='ROUTE',
        ),
        migrations.AddField(
            model_name='trip',
            name='ALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.allocation'),
            preserve_default=False,
        ),
    ]
