# Generated by Django 3.2.23 on 2024-08-22 10:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240703_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('lattitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('BUS', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='app.bus')),
            ],
        ),
    ]
