# Generated by Django 3.2.23 on 2024-08-22 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_track'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='BUS',
        ),
        migrations.AddField(
            model_name='track',
            name='ALLOCATION',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.allocation'),
            preserve_default=False,
        ),
    ]
