# Generated by Django 3.2.23 on 2024-08-22 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240822_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='ALLOCATION',
        ),
        migrations.AddField(
            model_name='track',
            name='TRIP',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.trip'),
            preserve_default=False,
        ),
    ]
