# Generated by Django 3.2.23 on 2024-08-26 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240822_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='TRIP',
        ),
        migrations.AddField(
            model_name='track',
            name='DRIVER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.driver'),
            preserve_default=False,
        ),
    ]
