# Generated by Django 3.2.23 on 2024-08-29 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_trip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
    ]
