# Generated by Django 3.2.23 on 2024-08-30 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='status',
            new_name='Bus_status',
        ),
        migrations.RemoveField(
            model_name='bus_status',
            name='DRIVER',
        ),
        migrations.AddField(
            model_name='bus_status',
            name='BUS',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.bus'),
            preserve_default=False,
        ),
    ]
